import LoadableComponent from './../Loadable/index';

export const userRouter: any = [
  {
    path: '/',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('src/components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('src/scenes/Login')),
    showInMenu: false,

  },
  {
    path: '/Desktop_Login',
    name: 'desktop_Login',
    title: 'Desktop_Login',
    component: LoadableComponent(() => import('src/scenes/Desktop_Login')),
    showInMenu: false,
  },
  {
    path: '/register',
    name: 'rgister',
    title: 'Register',
    component: LoadableComponent(() => import('src/scenes/Register')),
    showInMenu: true,
    isLayout: false,

  },
  {
    path: '/SearchResult',
    name: 'searchResult',
    title: 'SearchResult',
    component: LoadableComponent(() => import('src/scenes/SearchResult')),
    showInMenu: false,
  },
  {
    path: '/SearchResultDetail',
    name: 'searchResult',
    title: 'SearchResult',
    component: LoadableComponent(() => import('src/scenes/SearchResultDetail')),
    showInMenu: false,
  },
  {
    path: '/ViewProfile',
    name: 'ViewProfile',
    title: 'ViewProfile',
    component: LoadableComponent(() => import('src/scenes/ViewProfile')),
    showInMenu: false,
    isLayout: false,
  },
  {
    path: '/Rating',
    title: 'Ratings',
    name: 'Rating',
    icon: 'Rating',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/Rating')),
  },
  {
    path: '/AnotherRating',
    title: 'AnotherRating',
    name: 'AnotherRating',
    icon: 'AnotherRating',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/AnotherRating')),
  },
  {
    path: '/ChangeRating',
    title: 'ChangeRating',
    name: 'ChangeRating',
    icon: 'ChangeRating',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/ChangeRating')),
  },
  {
    path: '/CreateProfile',
    // permission: '',
    title: 'CreateProfile',
    name: 'CreateProfile',
    icon: 'CreateProfile',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/CreateProfile')),
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: 'home',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/Dashboard')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('src/components/Logout')),
  },
  {
    path: '/NewsFeeds',
    name: 'NewsFeeds',
    title: 'NewsFeeds',
    component: LoadableComponent(() => import('src/scenes/NewsFeeds')),
    showInMenu: false,
  }
];

export const appRouters: any = [
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: 'user',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: 'tags',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/Roles')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: 'appstore',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/Tenants')),
  },
  {
    path: '/about',
    permission: '',
    title: 'About',
    name: 'about',
    icon: 'info-circle',
    showInMenu: true,
    component: LoadableComponent(() => import('src/scenes/About')),
  },
  // {
  //   path: '/logout',
  //   permission: '',
  //   title: 'Logout',
  //   name: 'logout',
  //   icon: 'info-circle',
  //   showInMenu: false,
  //   component: LoadableComponent(() => import('src/components/Logout')),
  // },
  {
    path: '/exception',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('src/scenes/Exception')),
  },
];

export const routers = [...userRouter, ...appRouters];
